In [1]:
import datetime as dt
from datetime import date
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn import preprocessing

# Data Input, EDA & Preprocessing

## Individual Data Input

In [2]:
price_vol = pd.read_csv('../data/Price & Volume BTC.csv')
tweets = pd.read_csv('../data/Tweets.csv')
funding_rates_1600 = pd.read_csv('../data/Funding Rates BTCUSDT 1600.csv')
funding_rates_0800 = pd.read_csv('../data/Funding Rates BTCUSDT 0800.csv')
funding_rates_0000 = pd.read_csv('../data/Funding Rates BTCUSDT 0000.csv')
google = pd.read_csv('../data/Google.csv')
transactions = pd.read_csv('../data/Transactions.csv')
unique_addresses = pd.read_csv('../data/Unique Addresses.csv')
active_addresses = pd.read_csv('../data/Active Addresses.csv')

## Data Compilation

In [3]:
# get daily ave value for twitter attributes
tweets = tweets.groupby(by="Time").mean()
tweets = tweets.reset_index()

df = pd.merge(price_vol, funding_rates_0000, on=['Time'])
df = pd.merge(df, funding_rates_0800, on=['Time'])
df = pd.merge(df, funding_rates_1600, on=['Time'])
df = pd.merge(df, google, on=['Time'])
df = pd.merge(df, active_addresses, on=['Time'])
df = pd.merge(df, unique_addresses, on=['Time'])
df = pd.merge(df, transactions, on=['Time'])
df = pd.merge(tweets, df, how="outer")
df = df.drop(['Time'], axis=1)
df.head()

,Favorites,Retweets,Compound,Negative,Positive,Neutral,Open,Close,High,Low,Amount,Volume,Funding Rate 0000,Funding Rate 0800,Funding Rate 1600,Bitcoin_SVI,Cryptocurrency_SVI,No. of Active Addresses,No. of Unique Addresses,Transactions
0,5.0,2.0,0.0772,0.091,0.100,0.809,7933.2,4802.9,7960.4,4448.6,8901.930855,55248355.79,0.02%,0.01%,0.01%,22.83,6.20,909601,653156.0,349978.0
1,98.0,96.0,0.4019,0.000,0.114,0.886,5028.8,5316.7,5532.0,4926.1,3451.659903,18269210.08,-0.09%,-0.02%,0.00%,10.21,3.39,765477,540902.0,278326.0
2,125.0,95.0,0.4767,0.000,0.146,0.854,6162.2,6204.4,6901.7,5661.9,5948.954449,37752569.82,-0.03%,-0.02%,0.00%,10.04,3.56,734614,564748.0,284594.0
3,3.0,0.0,0.0803,0.061,0.071,0.869,5881.3,6394.9,6600.0,5860.0,2844.033767,17904828.40,-0.03%,-0.06%,-0.03%,5.92,3.63,770915,535787.0,276828.0
4,186.0,142.0,0.6597,0.000,0.278,0.722,6395.0,6409.7,6520.0,6288.0,2045.463979,13159710.94,-0.01%,-0.01%,-0.02%,5.45,3.54,816889,546702.0,290227.0

In [4]:
print("Type of variables: ", "\n", df.dtypes)

Type of variables:
 Favorites                  float64
Retweets                   float64
Compound                   float64
Negative                   float64
Positive                   float64
Neutral                    float64
Open                       float64
Close                      float64
High                       float64
Low                        float64
Amount                     float64
Volume                     float64
Funding Rate 0000           object
Funding Rate 0800           object
Funding Rate 1600           object
Bitcoin_SVI                float64
Cryptocurrency_SVI         float64
No. of Active Addresses      int64
No. of Unique Addresses    float64
Transactions               float64
dtype: object

# EDA & Preprocessing

In [6]:
# Select features, the target output is'Amount'
feature_pool = ['Favorites','Retweets','Compound','Negative','Positive',\
                'Neutral','Open','Close','High','Low',\
                'Volume','Funding Rate 0000','Funding Rate 0800','Funding Rate 1600','Bitcoin_SVI',\
                'Cryptocurrency_SVI','No. of Active Addresses','No. of Unique Addresses','Transactions']

output = 'Amount'

## Data Type Transformation

In [7]:
# Transform object type of "Funding Rate 0000", "Funding Rate 0800" and " Funding Rate 1600" to numerical type
df['Funding Rate 0000'] = df['Funding Rate 0000'].map(lambda x: float('nan') if pd.isnull(x) else float(x.replace('%','')))
df['Funding Rate 0800'] = df['Funding Rate 0800'].map(lambda x: float('nan') if pd.isnull(x) else float(x.replace('%','')))
df['Funding Rate 1600'] = df['Funding Rate 1600'].map(lambda x: float('nan') if pd.isnull(x) else float(x.replace('%','')))

## Train-Test Split

In [8]:
X, y = df.drop(output, axis=1), df[output]

# Split the data: train set: test set using = 70/30. Set random_state=42 so that results could be replicated.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
print(y_train.sum()/y_train.count(),y_test.sum()/y_test.count())

5211.226537039922 5330.696159252968

## Handle Missing Data

In [9]:
# Count missing value
print(df.isna().sum())

# check the consistency of columns with missing value between train set and the whole set
print(df[feature_pool].isnull().any().tolist()==X_train.isnull().any().tolist())
print(df[output].isnull().any().tolist()==y_train.isnull().any().tolist())

Favorites                  458
Retweets                   458
Compound                   458
Negative                   458
Positive                   458
Neutral                    458
Open                         0
Close                        0
High                         0
Low                          0
Amount                       0
Volume                       0
Funding Rate 0000            0
Funding Rate 0800            0
Funding Rate 1600            0
Bitcoin_SVI                  0
Cryptocurrency_SVI           0
No. of Active Addresses      0
No. of Unique Addresses      2
Transactions                 0
dtype: int64
True
True

## Monthly Sentiment Analysis

In [38]:
tweets.insert(1, "Month", "NaN")

tweets['Month'] = tweets['Time'].str[:7]
tweets.head(10)

,Time,Month,Favorites,Retweets,Text,Clean Tweet,Compound,Negative,Positive,Neutral
0,2022-03-03,2022-03,3139,466,U.S. senator Ted Cruz: Texas should be ground ...,U.S. senator Ted Cruz: Texas should be ground ...,0.0000,0.000,0.000,1.000
1,2022-03-03,2022-03,125,16,CleanSpark announced their #bitcoin production...,"CleanSpark announced their production for , ...",0.0000,0.000,0.000,1.000
2,2022-03-03,2022-03,2070,228,NEW: #Bitcoin miner CleanSpark produced 276 BT...,NEW: miner CleanSpark produced BTC worth mo...,0.2263,0.000,0.160,0.840
3,2022-03-03,2022-03,48,12,“The first phase was morphing GoFundMe to use ...,“ first phase was morphing GoFundMe to use cr...,0.3182,0.000,0.069,0.931
4,2022-03-03,2022-03,60,16,The stablecoin supply ratio has risen over the...,stablecoin supply ratio has risen over the p...,-0.2263,0.049,0.000,0.951
5,2022-03-03,2022-03,64,24,There's a growing trend of exclusive crypto so...,re's a growing trend of exclusive crypto soci...,0.2960,0.000,0.084,0.916
6,2022-03-03,2022-03,68,21,Calls to “crack down” on crypto are imprecise....,Calls to “crack down” on crypto are imprecise....,0.5859,0.000,0.138,0.862
7,2022-03-03,2022-03,60,22,"“It’s the first step in the crawl, walk, run.”...","“ ’s the first step in the crawl, walk, run.” ...",0.0000,0.000,0.000,1.000
8,2022-03-03,2022-03,80,20,MARKET WRAP: Bitcoin $BTC and other cryptos tr...,MARKET WRAP: B coin $BTC and other cryptos tra...,0.2023,0.143,0.133,0.724
9,2022-03-03,2022-03,88,40,The Russia-Ukraine conflict has sent crude oil...,Russia-Ukraine conflict has sent crude oil t...,-0.7184,0.240,0.000,0.760

In [ ]:
tweets = tweets.groupby(by="Month").mean()
tweets = tweets.reset_index()

In [10]:
tweets.head(10)

         Time  Favorites  Retweets  Compound  Negative  Positive  Neutral
0  2020-03-12        5.0       2.0    0.0772     0.091     0.100    0.809
1  2020-03-17       98.0      96.0    0.4019     0.000     0.114    0.886
2  2020-03-20      125.0      95.0    0.4767     0.000     0.146    0.854
3  2020-03-30        3.0       0.0    0.0803     0.061     0.071    0.869
4  2020-03-31      186.0     142.0    0.6597     0.000     0.278    0.722
5  2020-04-01      171.0     120.0    0.5267     0.061     0.184    0.754
6  2020-04-16      419.0      94.0    0.0000     0.000     0.000    1.000
7  2020-04-22       73.0      18.0    0.3182     0.000     0.084    0.916
8  2020-04-30      994.0     153.0    0.0000     0.000     0.000    1.000
9  2020-05-09       35.0       2.0    0.0000     0.000     0.000    1.000

In [48]:
df.insert(1, "Month", "NaN")

df['Month'] = df['Time'].str[:7]
df = pd.merge(df, tweets, on=['Month'])
df = df[['Time', 'Open', 'Close', 'High', 'Low', 'Amount', 'Volume', 'Funding Rate 0000', 'Funding Rate 0800', 'Funding Rate 1600', 'Bitcoin_SVI', 'Cryptocurrency_SVI', 'No. of Active Addresses', 'No. of Unique Addresses', 'Transactions', 'Favorites', 'Retweets', 'Compound', 'Negative', 'Positive', 'Neutral']]

df.head(10)

,Time,Open,Close,High,Low,Amount,Volume,Funding Rate 0000,Funding Rate 0800,Funding Rate 1600,...,Cryptocurrency_SVI,No. of Active Addresses,No. of Unique Addresses,Transactions,Favorites,Retweets,Compound,Negative,Positive,Neutral
0,2022-03-03,43896.8,42456.3,44088.0,41832.0,7550.686088,324545814.8,0.01%,0.01%,0.01%,...,24.08,1011448,701198.0,268244.0,438.725275,76.000000,0.056232,0.046714,0.067945,0.885363
1,2022-03-02,44428.2,43896.9,45367.5,43332.8,7712.371474,340460526.5,0.00%,0.00%,0.01%,...,26.33,1091796,731603.0,288657.0,438.725275,76.000000,0.056232,0.046714,0.067945,0.885363
2,2022-03-01,43174.8,44428.2,44966.0,42796.9,10184.794790,444858241.2,-0.01%,0.01%,0.01%,...,29.34,1065354,722863.0,280634.0,438.725275,76.000000,0.056232,0.046714,0.067945,0.885363
3,2022-02-28,37706.7,43179.8,44210.4,37446.5,14045.290600,564121052.5,0.00%,-0.02%,-0.01%,...,24.83,981066,702483.0,270918.0,780.201681,121.352941,0.119577,0.045210,0.083269,0.871504
4,2022-02-27,39117.3,37706.7,39864.0,36977.4,10079.638300,388368905.7,0.01%,0.01%,0.00%,...,21.07,768705,583361.0,211164.0,780.201681,121.352941,0.119577,0.045210,0.083269,0.871504
5,2022-02-26,39219.6,39119.1,40300.0,38560.3,7813.061179,306410979.9,0.00%,0.01%,0.01%,...,16.17,818914,582374.0,220423.0,780.201681,121.352941,0.119577,0.045210,0.083269,0.871504
6,2022-02-25,38320.9,39219.6,39695.0,38015.0,9925.502518,386047125.7,-0.01%,0.01%,0.01%,...,19.52,936543,687447.0,260340.0,780.201681,121.352941,0.119577,0.045210,0.083269,0.871504
7,2022-02-24,37248.2,38320.9,39823.3,34325.0,18871.390610,680985023.6,0.00%,0.01%,-0.02%,...,23.42,958866,676575.0,254139.0,780.201681,121.352941,0.119577,0.045210,0.083269,0.871504
8,2022-02-23,38229.6,37248.1,39285.2,37046.8,8656.548723,331098529.4,0.00%,0.00%,-0.01%,...,20.07,859810,622682.0,251275.0,780.201681,121.352941,0.119577,0.045210,0.083269,0.871504
9,2022-02-22,37020.5,38229.6,38448.4,36333.1,8650.227539,324319840.5,0.00%,-0.01%,0.00%,...,22.86,886571,647191.0,260265.0,780.201681,121.352941,0.119577,0.045210,0.083269,0.871504

In [11]:
KNN_miss_filling = KNNImputer(n_neighbors=2).fit(X_train)
X_train = pd.DataFrame(KNN_miss_filling.transform(X_train), columns=feature_pool)
X_test = pd.DataFrame(KNN_miss_filling.transform(X_test), columns=feature_pool)

In [12]:
print(X_train.isna().sum())
print(X_test.isna().sum())

Favorites                  0
Retweets                   0
Compound                   0
Negative                   0
Positive                   0
Neutral                    0
Open                       0
Close                      0
High                       0
Low                        0
Volume                     0
Funding Rate 0000          0
Funding Rate 0800          0
Funding Rate 1600          0
Bitcoin_SVI                0
Cryptocurrency_SVI         0
No. of Active Addresses    0
No. of Unique Addresses    0
Transactions               0
dtype: int64
Favorites                  0
Retweets                   0
Compound                   0
Negative                   0
Positive                   0
Neutral                    0
Open                       0
Close                      0
High                       0
Low                        0
Volume                     0
Funding Rate 0000          0
Funding Rate 0800          0
Funding Rate 1600          0
Bitcoin_SVI                0
Cryptocurrency_SVI         0
No. of Active Addresses    0
No. of Unique Addresses    0
Transactions               0
dtype: int64